#!/usr/bin/env python3
"""Render the generated parts of the shipcrew agent bundles.

Omnigent bundles cannot include files from outside their own directory: the
spec parser only reads an ``instructions:`` file contained in the bundle root
(anything else is taken as literal prompt text), and YAML has no include.
So the shared sources live in ``agents/_shared/`` and this script renders them
into each bundle:

* ``agents/<role>/AGENTS.md``  = ``agents/<role>/ROLE.md`` + ``agents/_shared/COMMON.md``
* the ``guardrails:`` block of ``agents/<role>/config.yaml``, between the
  ``# >>> shipcrew-guardrails: <policy> ...`` and ``# <<< shipcrew-guardrails``
  markers, from the fragments in ``agents/_shared/policies/<policy>.yaml``.
  A fragment line ``# @include allowlists/<group>`` is replaced by the lines of
  ``agents/_shared/policies/allowlists/<group>.yaml``, at the same indentation
  (the per-role shell allowlists share their command groups this way).
* the MCP scoping of ``executor.config``, between the indented
  ``# >>> shipcrew-mcp: <server> ...`` and ``# <<< shipcrew-mcp`` markers, from
  ``agents/_shared/mcp/<server>.json`` (one server object each):
  ``strict_mcp_config: true`` always (the session gets none of the host user's
  own MCP servers, plugins or claude.ai connectors), ``setting_sources:
  project,local`` (no ``~/.claude/settings.json``: no user plugins, hooks or
  skills), plus ``mcp_config`` with the listed servers. omnigent turns them into ``--strict-mcp-config`` /
  ``--mcp-config`` (``omnigent/shipcrew/launch_args.py`` in the fork); its own
  relay (``sys_*`` tools) is added on top.

Edit ROLE.md, COMMON.md or a policy fragment, then run::

    python3 scripts/build_agents.py          # rewrite generated files
    python3 scripts/build_agents.py --check  # exit 1 if anything is stale

Standard library only, so it runs without the omnigent environment.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AGENTS = REPO / "agents"
SHARED = AGENTS / "_shared"
COMMON = SHARED / "COMMON.md"
POLICIES = SHARED / "policies"
MCP = SHARED / "mcp"

# Approvals (ASK) wait a full day: an approval card should outlive a human
# stepping away, as in omnigent's polly.
ASK_TIMEOUT = 86400
# Claude setting sources every session loads: never "user" (the host user's
# plugins, SessionStart hooks and skills would leak into the crew).
SETTING_SOURCES = "project,local"

_INCLUDE_RE = re.compile(r"^(?P<indent>[ \t]*)# @include (?P<name>[A-Za-z0-9_./-]+)[ \t]*$")

_MARKER_RE = re.compile(
    r"^# >>> shipcrew-guardrails:(?P<names>[^\n]*)\n.*?^# <<< shipcrew-guardrails[^\n]*\n",
    re.MULTILINE | re.DOTALL,
)


_MCP_MARKER_RE = re.compile(
    r"^(?P<indent>[ \t]*)# >>> shipcrew-mcp:(?P<names>[^\n]*)\n.*?^[ \t]*# <<< shipcrew-mcp[^\n]*\n",
    re.MULTILINE | re.DOTALL,
)


def bundle_dirs() -> list[Path]:
    """Return every bundle directory (has a config.yaml), ``_shared`` excluded."""
    return sorted(
        p
        for p in AGENTS.iterdir()
        if p.is_dir() and not p.name.startswith(("_", ".")) and (p / "config.yaml").is_file()
    )


def render_agents_md(bundle: Path) -> str:
    """ROLE.md followed by the shared COMMON.md, with a do-not-edit header."""
    role = (bundle / "ROLE.md").read_text(encoding="utf-8").rstrip()
    common = COMMON.read_text(encoding="utf-8").rstrip()
    header = (
        f"<!-- GENERATED by scripts/build_agents.py from agents/{bundle.name}/ROLE.md"
        " + agents/_shared/COMMON.md. Do not edit: edit the sources and re-run. -->"
    )
    return f"{header}\n\n{role}\n\n---\n\n{common}\n"


def expand_includes(text: str, *, depth: int = 0) -> list[str]:
    """Lines of a fragment with its ``# @include <path>`` lines expanded."""
    if depth > 4:
        raise ValueError("shipcrew policy includes nested too deep")
    lines: list[str] = []
    for line in text.rstrip().splitlines():
        match = _INCLUDE_RE.match(line)
        if match is None:
            lines.append(line)
            continue
        included = POLICIES / f"{match['name']}.yaml"
        if not included.is_file() or POLICIES.resolve() not in included.resolve().parents:
            raise FileNotFoundError(f"unknown shipcrew policy include: {included}")
        indent = match["indent"]
        for sub in expand_includes(included.read_text(encoding="utf-8"), depth=depth + 1):
            lines.append(f"{indent}{sub}" if sub else "")
    return lines


def render_guardrails(names: list[str]) -> str:
    """The ``guardrails:`` YAML block built from the named policy fragments."""
    if not names:
        raise ValueError("shipcrew-guardrails marker lists no policies")
    lines = [
        f"# >>> shipcrew-guardrails: {' '.join(names)}",
        "# GENERATED from agents/_shared/policies/*.yaml by scripts/build_agents.py.",
        "guardrails:",
        f"  ask_timeout: {ASK_TIMEOUT}",
        "  policies:",
    ]
    for name in names:
        fragment = POLICIES / f"{name}.yaml"
        if not fragment.is_file():
            raise FileNotFoundError(f"unknown shipcrew policy fragment: {fragment}")
        for line in expand_includes(fragment.read_text(encoding="utf-8")):
            lines.append(f"    {line}" if line else "")
    lines.append("# <<< shipcrew-guardrails")
    return "\n".join(lines) + "\n"


def mcp_servers(names: list[str]) -> dict[str, object]:
    """``{"mcpServers": {...}}`` built from the named ``_shared/mcp`` fragments."""
    servers: dict[str, object] = {}
    for name in names:
        fragment = MCP / f"{name}.json"
        if not fragment.is_file():
            raise FileNotFoundError(f"unknown shipcrew MCP server fragment: {fragment}")
        server = json.loads(fragment.read_text(encoding="utf-8"))
        if not isinstance(server, dict) or "command" not in server:
            raise ValueError(f"{fragment}: expected a server object with a command")
        servers[name] = server
    return {"mcpServers": servers}


def render_mcp(names: list[str], indent: str) -> str:
    """The ``strict_mcp_config`` / ``mcp_config`` lines for an executor.config block."""
    lines = [
        f"# >>> shipcrew-mcp:{''.join(' ' + n for n in names)}",
        "# GENERATED from agents/_shared/mcp/*.json by scripts/build_agents.py.",
        "# Only these MCP servers (plus omnigent's relay), never the host user's own.",
        "strict_mcp_config: true",
        "# No host-user settings (~/.claude/settings.json: their plugins, hooks,",
        "# user skills); the bundle's own skills still load (--plugin-dir).",
        f"setting_sources: {SETTING_SOURCES}",
    ]
    if names:
        payload = json.dumps(mcp_servers(names), separators=(",", ":"))
        # A single-quoted YAML scalar: only ' needs escaping (as '').
        quoted = payload.replace("'", "''")
        lines.append(f"mcp_config: '{quoted}'")
    lines.append("# <<< shipcrew-mcp")
    return "".join(f"{indent}{line}\n" for line in lines)


def render_config(config_text: str, path: Path) -> str:
    """Replace the guardrails and MCP marker regions of *config_text*."""
    match = _MARKER_RE.search(config_text)
    if match is None:
        raise ValueError(f"{path}: missing '# >>> shipcrew-guardrails:' ... '# <<<' markers")
    names = match.group("names").split()
    text = config_text[: match.start()] + render_guardrails(names) + config_text[match.end() :]
    mcp = _MCP_MARKER_RE.search(text)
    if mcp is None:
        raise ValueError(f"{path}: missing '# >>> shipcrew-mcp:' ... '# <<<' markers")
    block = render_mcp(mcp.group("names").split(), mcp.group("indent"))
    return text[: mcp.start()] + block + text[mcp.end() :]


def build(check: bool) -> list[Path]:
    """Render every bundle; return the files that were (or would be) changed."""
    changed: list[Path] = []
    for bundle in bundle_dirs():
        targets: list[tuple[Path, str]] = []
        if (bundle / "ROLE.md").is_file():
            targets.append((bundle / "AGENTS.md", render_agents_md(bundle)))
        config = bundle / "config.yaml"
        targets.append((config, render_config(config.read_text(encoding="utf-8"), config)))
        for path, content in targets:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != content:
                changed.append(path)
                if not check:
                    path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    changed = build(check=args.check)
    for path in changed:
        verb = "stale" if args.check else "wrote"
        print(f"{verb}: {path.relative_to(REPO)}")
    if args.check and changed:
        print("run: python3 scripts/build_agents.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
