#!/usr/bin/env python3
"""Render the generated parts of the shipcrew agent bundles.

Omnigent bundles cannot include files from outside their own directory: the
spec parser only reads an ``instructions:`` file contained in the bundle root
(anything else is taken as literal prompt text), and YAML has no include.
So the shared sources live in ``agents/_shared/`` and this script renders them
into each bundle:

* ``agents/<role>/AGENTS.md``  = ``agents/<role>/ROLE.md`` + ``agents/_shared/COMMON.md``
* the ``guardrails:`` block of ``agents/<role>/config.yaml``, between the
  ``# >>> shipcrew-guardrails: <policy> ...`` and ``# <<< shipcrew-guardrails``
  markers, from the fragments in ``agents/_shared/policies/<policy>.yaml``.
  A fragment line ``# @include allowlists/<group>`` is replaced by the lines of
  ``agents/_shared/policies/allowlists/<group>.yaml``, at the same indentation
  (the per-role shell allowlists share their command groups this way).

Edit ROLE.md, COMMON.md or a policy fragment, then run::

    python3 scripts/build_agents.py          # rewrite generated files
    python3 scripts/build_agents.py --check  # exit 1 if anything is stale

Standard library only, so it runs without the omnigent environment.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
AGENTS = REPO / "agents"
SHARED = AGENTS / "_shared"
COMMON = SHARED / "COMMON.md"
POLICIES = SHARED / "policies"

# Approvals (ASK) wait a full day: an approval card should outlive a human
# stepping away, as in omnigent's polly.
ASK_TIMEOUT = 86400

_INCLUDE_RE = re.compile(r"^(?P<indent>[ \t]*)# @include (?P<name>[A-Za-z0-9_./-]+)[ \t]*$")

_MARKER_RE = re.compile(
    r"^# >>> shipcrew-guardrails:(?P<names>[^\n]*)\n.*?^# <<< shipcrew-guardrails[^\n]*\n",
    re.MULTILINE | re.DOTALL,
)


def bundle_dirs() -> list[Path]:
    """Return every bundle directory (has a config.yaml), ``_shared`` excluded."""
    return sorted(
        p
        for p in AGENTS.iterdir()
        if p.is_dir() and not p.name.startswith(("_", ".")) and (p / "config.yaml").is_file()
    )


def render_agents_md(bundle: Path) -> str:
    """ROLE.md followed by the shared COMMON.md, with a do-not-edit header."""
    role = (bundle / "ROLE.md").read_text(encoding="utf-8").rstrip()
    common = COMMON.read_text(encoding="utf-8").rstrip()
    header = (
        f"<!-- GENERATED by scripts/build_agents.py from agents/{bundle.name}/ROLE.md"
        " + agents/_shared/COMMON.md. Do not edit: edit the sources and re-run. -->"
    )
    return f"{header}\n\n{role}\n\n---\n\n{common}\n"


def expand_includes(text: str, *, depth: int = 0) -> list[str]:
    """Lines of a fragment with its ``# @include <path>`` lines expanded."""
    if depth > 4:
        raise ValueError("shipcrew policy includes nested too deep")
    lines: list[str] = []
    for line in text.rstrip().splitlines():
        match = _INCLUDE_RE.match(line)
        if match is None:
            lines.append(line)
            continue
        included = POLICIES / f"{match['name']}.yaml"
        if not included.is_file() or POLICIES.resolve() not in included.resolve().parents:
            raise FileNotFoundError(f"unknown shipcrew policy include: {included}")
        indent = match["indent"]
        for sub in expand_includes(included.read_text(encoding="utf-8"), depth=depth + 1):
            lines.append(f"{indent}{sub}" if sub else "")
    return lines


def render_guardrails(names: list[str]) -> str:
    """The ``guardrails:`` YAML block built from the named policy fragments."""
    if not names:
        raise ValueError("shipcrew-guardrails marker lists no policies")
    lines = [
        f"# >>> shipcrew-guardrails: {' '.join(names)}",
        "# GENERATED from agents/_shared/policies/*.yaml by scripts/build_agents.py.",
        "guardrails:",
        f"  ask_timeout: {ASK_TIMEOUT}",
        "  policies:",
    ]
    for name in names:
        fragment = POLICIES / f"{name}.yaml"
        if not fragment.is_file():
            raise FileNotFoundError(f"unknown shipcrew policy fragment: {fragment}")
        for line in expand_includes(fragment.read_text(encoding="utf-8")):
            lines.append(f"    {line}" if line else "")
    lines.append("# <<< shipcrew-guardrails")
    return "\n".join(lines) + "\n"


def render_config(config_text: str, path: Path) -> str:
    """Replace the guardrails marker region of *config_text*."""
    match = _MARKER_RE.search(config_text)
    if match is None:
        raise ValueError(f"{path}: missing '# >>> shipcrew-guardrails:' ... '# <<<' markers")
    names = match.group("names").split()
    return config_text[: match.start()] + render_guardrails(names) + config_text[match.end() :]


def build(check: bool) -> list[Path]:
    """Render every bundle; return the files that were (or would be) changed."""
    changed: list[Path] = []
    for bundle in bundle_dirs():
        targets: list[tuple[Path, str]] = []
        if (bundle / "ROLE.md").is_file():
            targets.append((bundle / "AGENTS.md", render_agents_md(bundle)))
        config = bundle / "config.yaml"
        targets.append((config, render_config(config.read_text(encoding="utf-8"), config)))
        for path, content in targets:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != content:
                changed.append(path)
                if not check:
                    path.write_text(content, encoding="utf-8")
    return changed


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()
    changed = build(check=args.check)
    for path in changed:
        verb = "stale" if args.check else "wrote"
        print(f"{verb}: {path.relative_to(REPO)}")
    if args.check and changed:
        print("run: python3 scripts/build_agents.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
